# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Generate draw.io diagrams
      - name: Generate diagrams
        uses: docker://ghcr.io/racklet/render-drawio-action:v1.0.3
        id: render
        with:
          sub-dirs: 'diagrams'
      - name: List diagrams
        run: 'ls -l ${{ steps.render.outputs.rendered-files }}'
      - uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'Automatically generation of .drawio images'
          add: "${{ steps.render.outputs.rendered-files }}"
        if: "${{ steps.render.outputs.rendered-files != ''}}"
